import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  pltSidebar: [{type: 'autogenerated', dirName: 'plt'}],
  linuxSidebar: [{type: 'autogenerated', dirName: 'linux'}],
  madtSideBar: [{type: 'autogenerated', dirName: 'madt'}],
  workshopSidebar: [{type: 'autogenerated', dirName: 'workshop'}],
  webii: [{type: 'autogenerated', dirName: 'webii'}],
  bssSidebar: [{type: 'autogenerated', dirName: 'business support system'}],
  mlSidebar: [{type: 'autogenerated', dirName: 'machine learning'}],
  project: [{type: 'autogenerated', dirName: 'project'}],
};

export default sidebars;